#pragma once
#include "CStateIdle.h"
#include "CStateMove.h"
#include "CStateJump.h"
#include "CStateFall.h"
#include "CStateAttack.h"
#include "CStateDash.h"
#include "CStateDie.h"
#include "CStateTrace.h"
#include "CStateSkill.h"
#include "CStateAppear.h"
#include "CStateJumpAttack.h"

#include "CBossStateIdle.h"
#include "CBossStateIdleP2.h"
#include "CBossStateSlam.h"
#include "CBossStateSweep.h"
#include "CBossStateChange.h"
#include "CBossStateBomb.h"

#include "CBossStateIdleP2.h"